# Use an official Ruby image as a base
FROM ruby:2.7

# Install Node.js and other dependencies if necessary
RUN apt-get update && apt-get install -y openjdk-17-jdk maven

RUN apt-get install -y build-essential

# Install License Finder gem
RUN gem install license_finder

# Set the working directory inside the container
WORKDIR /scan

# Set the entrypoint to the script
ENTRYPOINT ["license_finder"]
